In [3]:
import pandas as pd 
import numpy as np
pd.set_option('display.max_columns',None)
pd.set_option('display.float_format','{:.2f}'.format)

#### Data Cleaning & Feature Engineering

This notebook prepares retail transactional data for business analysis by performing
data quality checks, cleaning, and feature engineering.

In [4]:
df = pd.read_csv(r"C:\Users\shubu\Documents\Business-Performance-Analytics\Data\raw\superstore_raw.csv")
df.head()

,Category,City,Country,Customer.ID,Customer.Name,Discount,Market,Order.Date,Order.ID,Order.Priority,Product.ID,Product.Name,Profit,Quantity,Region,Row.ID,Sales,Segment,Ship.Date,Ship.Mode,Shipping.Cost,State,Sub.Category,Year,Market2,weeknum
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.00,US,00:00.0,CA-2011-130813,High,OFF-PA-10002005,Xerox 225,9.33,3,West,36624,19,Consumer,00:00.0,Second Class,4.37,California,Paper,2011,North America,2
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.00,US,00:00.0,CA-2011-148614,Medium,OFF-PA-10002893,"Wirebound Service Call Books, 5 1/2"" x 4""",9.29,2,West,37033,19,Consumer,00:00.0,Standard Class,0.94,California,Paper,2011,North America,4
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.00,US,00:00.0,CA-2011-118962,Medium,OFF-PA-10000659,"Adams Phone Message Book, Professional, 400 Me...",9.84,3,West,31468,21,Consumer,00:00.0,Standard Class,1.81,California,Paper,2011,North America,32
3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.00,US,00:00.0,CA-2011-118962,Medium,OFF-PA-10001144,Xerox 1913,53.26,2,West,31469,111,Consumer,00:00.0,Standard Class,4.59,California,Paper,2011,North America,32
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.00,US,00:00.0,CA-2011-146969,High,OFF-PA-10002105,Xerox 223,3.11,1,West,32440,6,Consumer,00:00.0,Standard Class,1.32,California,Paper,2011,North America,40

In [5]:
df.shape # rows and columns

(51290, 26)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Category        51290 non-null  object
 1   City            51290 non-null  object
 2   Country         51290 non-null  object
 3   Customer.ID     51290 non-null  object
 4   Customer.Name   51290 non-null  object
 5   Discount        51290 non-null  float64
 6   Market          51290 non-null  object
 7   Order.Date      51290 non-null  object
 8   Order.ID        51290 non-null  object
 9   Order.Priority  51290 non-null  object
 10  Product.ID      51290 non-null  object
 11  Product.Name    51290 non-null  object
 12  Profit          51290 non-null  float64
 13  Quantity        51290 non-null  int64
 14  Region          51290 non-null  object
 15  Row.ID          51290 non-null  int64
 16  Sales           51290 non-null  int64
 17  Segment         51290 non-null  object
 18  Ship.Date       51290 non-null  object
 19  Ship.Mode       51290 non-null  object
 20  Shipping.Cost   51290 non-null  float64
 21  State           51290 non-null  object
 22  Sub.Category    51290 non-null  object
 23  Year            51290 non-null  int64
 24  Market2         51290 non-null  object
 25  weeknum         51290 non-null  int64
dtypes: float64(3), int64(5), object(18)
memory usage: 10.2+ MB

In [7]:
df.head(10)

,Category,City,Country,Customer.ID,Customer.Name,Discount,Market,Order.Date,Order.ID,Order.Priority,Product.ID,Product.Name,Profit,Quantity,Region,Row.ID,Sales,Segment,Ship.Date,Ship.Mode,Shipping.Cost,State,Sub.Category,Year,Market2,weeknum
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.00,US,00:00.0,CA-2011-130813,High,OFF-PA-10002005,Xerox 225,9.33,3,West,36624,19,Consumer,00:00.0,Second Class,4.37,California,Paper,2011,North America,2
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.00,US,00:00.0,CA-2011-148614,Medium,OFF-PA-10002893,"Wirebound Service Call Books, 5 1/2"" x 4""",9.29,2,West,37033,19,Consumer,00:00.0,Standard Class,0.94,California,Paper,2011,North America,4
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.00,US,00:00.0,CA-2011-118962,Medium,OFF-PA-10000659,"Adams Phone Message Book, Professional, 400 Me...",9.84,3,West,31468,21,Consumer,00:00.0,Standard Class,1.81,California,Paper,2011,North America,32
3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.00,US,00:00.0,CA-2011-118962,Medium,OFF-PA-10001144,Xerox 1913,53.26,2,West,31469,111,Consumer,00:00.0,Standard Class,4.59,California,Paper,2011,North America,32
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.00,US,00:00.0,CA-2011-146969,High,OFF-PA-10002105,Xerox 223,3.11,1,West,32440,6,Consumer,00:00.0,Standard Class,1.32,California,Paper,2011,North America,40
5,Office Supplies,Los Angeles,United States,JF-154904,Jeremy Farry,0.00,US,00:00.0,CA-2011-117317,Critical,OFF-PA-10004519,Spiral Phone Message Books with Labels by Adams,6.59,3,West,32890,13,Consumer,00:00.0,Same Day,2.39,California,Paper,2011,North America,43
6,Office Supplies,Los Angeles,United States,WB-218504,William Brown,0.00,US,00:00.0,CA-2011-125829,Medium,OFF-PA-10000223,Xerox 2000,9.33,3,West,35608,19,Consumer,00:00.0,Standard Class,1.15,California,Paper,2011,North America,45
7,Office Supplies,Los Angeles,United States,JA-159704,Joseph Airdo,0.00,US,00:00.0,CA-2011-151295,High,OFF-PA-10001947,Xerox 1974,5.86,2,West,33709,12,Consumer,00:00.0,Standard Class,0.92,California,Paper,2011,North America,46
8,Office Supplies,Los Angeles,United States,SP-209204,Susan Pistek,0.00,US,00:00.0,CA-2011-135090,High,OFF-PA-10002245,Xerox 1895,24.22,9,West,35267,54,Consumer,00:00.0,Standard Class,6.98,California,Paper,2011,North America,48
9,Office Supplies,Los Angeles,United States,RL-196154,Rob Lucas,0.00,US,00:00.0,CA-2011-133830,Medium,OFF-PA-10001363,Xerox 1933,23.09,4,West,38866,49,Consumer,00:00.0,Standard Class,1.99,California,Paper,2011,North America,50

In [8]:
df.tail(5)

,Category,City,Country,Customer.ID,Customer.Name,Discount,Market,Order.Date,Order.ID,Order.Priority,Product.ID,Product.Name,Profit,Quantity,Region,Row.ID,Sales,Segment,Ship.Date,Ship.Mode,Shipping.Cost,State,Sub.Category,Year,Market2,weeknum
51285,Office Supplies,Los Angeles,United States,AM-103604,Alice McCarthy,0.20,US,00:00.0,CA-2014-109701,High,OFF-BI-10000632,Satellite Sectional Post Binders,22.57,2,West,33646,69,Corporate,00:00.0,Same Day,5.15,California,Binders,2014,North America,49
51286,Office Supplies,Los Angeles,United States,AM-103604,Alice McCarthy,0.20,US,00:00.0,CA-2014-109701,High,OFF-BI-10004187,Staples,3.16,6,West,33645,9,Corporate,00:00.0,Same Day,0.44,California,Binders,2014,North America,49
51287,Office Supplies,Los Angeles,United States,HR-147704,Hallie Redmond,0.20,US,00:00.0,CA-2014-106964,Medium,OFF-BI-10000320,GBC Plastic Binding Combs,4.28,2,West,32321,12,Home Office,00:00.0,First Class,0.31,California,Binders,2014,North America,51
51288,Office Supplies,Los Angeles,United States,RM-196754,Robert Marley,0.20,US,00:00.0,CA-2014-145219,Critical,OFF-BI-10001670,Vinyl Sectional Post Binders,33.93,3,West,35917,90,Home Office,00:00.0,First Class,15.95,California,Binders,2014,North America,52
51289,Office Supplies,Los Angeles,United States,FH-143654,Fred Hopkins,0.20,US,00:00.0,CA-2014-121398,Medium,OFF-BI-10001718,GBC DocuBind P50 Personal Binding Machine,51.82,3,West,37371,154,Corporate,00:00.0,Standard Class,9.59,California,Binders,2014,North America,52

In [9]:
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(' ', '_')
      .str.replace('-', '_')
      .str.replace('.','_', regex = False)
)

df.columns

Index(['category', 'city', 'country', 'customer_id', 'customer_name',
       'discount', 'market', 'order_date', 'order_id', 'order_priority',
       'product_id', 'product_name', 'profit', 'quantity', 'region', 'row_id',
       'sales', 'segment', 'ship_date', 'ship_mode', 'shipping_cost', 'state',
       'sub_category', 'year', 'market2', 'weeknum'],
      dtype='object')

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.isnull().sum().sort_values(ascending = False)

category          0
city              0
country           0
customer_id       0
customer_name     0
discount          0
market            0
order_date        0
order_id          0
order_priority    0
product_id        0
product_name      0
profit            0
quantity          0
region            0
row_id            0
sales             0
segment           0
ship_date         0
ship_mode         0
shipping_cost     0
state             0
sub_category      0
year              0
market2           0
weeknum           0
dtype: int64

In [12]:
df.dtypes

category           object
city               object
country            object
customer_id        object
customer_name      object
discount          float64
market             object
order_date         object
order_id           object
order_priority     object
product_id         object
product_name       object
profit            float64
quantity            int64
region             object
row_id              int64
sales               int64
segment            object
ship_date          object
ship_mode          object
shipping_cost     float64
state              object
sub_category       object
year                int64
market2            object
weeknum             int64
dtype: object

#### Data Quality Observations

- Column names have been standardized to snake_case for consistency and SQL compatibility
- No missing values were observed across any columns
- No fully duplicated rows were detected in the dataset
- Date-related columns (order_date, ship_date) are currently in string format and require conversion to datetime
- Numerical columns such as sales, profit, and discount appear correctly populated but require data type validation

In [13]:
df.columns

Index(['category', 'city', 'country', 'customer_id', 'customer_name',
       'discount', 'market', 'order_date', 'order_id', 'order_priority',
       'product_id', 'product_name', 'profit', 'quantity', 'region', 'row_id',
       'sales', 'segment', 'ship_date', 'ship_mode', 'shipping_cost', 'state',
       'sub_category', 'year', 'market2', 'weeknum'],
      dtype='object')

In [14]:
# Date conversion
df['order_date'] =pd.to_datetime(df['order_date'], errors ='coerce')
df['ship_date'] =pd.to_datetime(df['ship_date'], errors ='coerce')

In [15]:
# Verify
df[['order_date','ship_date']].dtypes

order_date    datetime64[ns]
ship_date     datetime64[ns]
dtype: object

In [16]:
# Numeric columns validation
numeric_columns =['sales','profit','discount','quantity','shipping_cost']
df[numeric_columns].dtypes

sales              int64
profit           float64
discount         float64
quantity           int64
shipping_cost    float64
dtype: object

In [17]:
df[numeric_columns].describe()

         sales   profit  discount  quantity  shipping_cost
count 51290.00 51290.00  51290.00  51290.00       51290.00
mean    246.50    28.61      0.14      3.48          26.38
std     487.57   174.34      0.21      2.28          57.30
min       0.00 -6599.98      0.00      1.00           0.00
25%      31.00     0.00      0.00      2.00           2.61
50%      85.00     9.24      0.00      3.00           7.79
75%     251.00    36.81      0.20      5.00          24.45
max   22638.00  8399.98      0.85     14.00         933.57

#### Data Type Validation

- Column names standardized using underscores for SQL and BI compatibility
- order_date and ship_date converted to datetime format successfully
- Sales, profit, discount, quantity, and shipping_cost validated as numeric
- No critical data conversion issues observed

In [18]:
# Revenue & Profitability Metrics
df['revenue'] = df['sales']
df['profit_margin'] = np.where(df['sales'] ==0,
                               0,df['profit'] / df['sales'])

In [19]:
# Discount amount
df['discount_amount'] = df['sales'] * df['discount']

In [20]:
# Time based features
df['order_year'] = df['order_date'].dt.year
df['order_month'] = df['order_date'].dt.month
df['order_month_name'] = df['order_date'].dt.month_name()

In [21]:
 # Business Flags
df['loss_making_flag'] = np.where(df['profit']<0,1,0)
df['high_discount_flag'] = np.where(df['discount']>0.25,1,0)

In [22]:
df[['revenue','profit','profit_margin','discount_amount','loss_making_flag','high_discount_flag']].head()

,revenue,profit,profit_margin,discount_amount,loss_making_flag,high_discount_flag
0,19,9.33,0.49,0.00,0,0
1,19,9.29,0.49,0.00,0,0
2,21,9.84,0.47,0.00,0,0
3,111,53.26,0.48,0.00,0,0
4,6,3.11,0.52,0.00,0,0

In [23]:
df[['loss_making_flag','high_discount_flag']].value_counts()

loss_making_flag  high_discount_flag
0                 0                     37714
1                 1                     10057
                  0                      2487
0                 1                      1032
Name: count, dtype: int64

#### Feature Engineering

The following business metrics and flags were created to support profitability and performance analysis:

- Revenue derived from sales values
- Profit margin calculated as profit divided by sales
- Discount amount calculated to quantify revenue impact
- Time-based features (year, month) extracted from order_date
- Loss-making flag to identify unprofitable transactions
- High discount flag to identify aggressive discounting

In [24]:
df.to_csv('../data/processed/superstore_cleaned.csv', index=False)

In [25]:
pd.read_csv('../data/processed/superstore_cleaned.csv').head()

,category,city,country,customer_id,customer_name,discount,market,order_date,order_id,order_priority,product_id,product_name,profit,quantity,region,row_id,sales,segment,ship_date,ship_mode,shipping_cost,state,sub_category,year,market2,weeknum,revenue,profit_margin,discount_amount,order_year,order_month,order_month_name,loss_making_flag,high_discount_flag
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.00,US,2026-01-28,CA-2011-130813,High,OFF-PA-10002005,Xerox 225,9.33,3,West,36624,19,Consumer,2026-01-28,Second Class,4.37,California,Paper,2011,North America,2,19,0.49,0.00,2026,1,January,0,0
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.00,US,2026-01-28,CA-2011-148614,Medium,OFF-PA-10002893,"Wirebound Service Call Books, 5 1/2"" x 4""",9.29,2,West,37033,19,Consumer,2026-01-28,Standard Class,0.94,California,Paper,2011,North America,4,19,0.49,0.00,2026,1,January,0,0
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.00,US,2026-01-28,CA-2011-118962,Medium,OFF-PA-10000659,"Adams Phone Message Book, Professional, 400 Me...",9.84,3,West,31468,21,Consumer,2026-01-28,Standard Class,1.81,California,Paper,2011,North America,32,21,0.47,0.00,2026,1,January,0,0
3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.00,US,2026-01-28,CA-2011-118962,Medium,OFF-PA-10001144,Xerox 1913,53.26,2,West,31469,111,Consumer,2026-01-28,Standard Class,4.59,California,Paper,2011,North America,32,111,0.48,0.00,2026,1,January,0,0
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.00,US,2026-01-28,CA-2011-146969,High,OFF-PA-10002105,Xerox 223,3.11,1,West,32440,6,Consumer,2026-01-28,Standard Class,1.32,California,Paper,2011,North America,40,6,0.52,0.00,2026,1,January,0,0

#### Summary

- Loaded and inspected raw retail sales data
- Standardized column naming for analytics compatibility
- Validated data quality and data types
- Engineered key business metrics including revenue, profit margin, discount amount, and profitability flags
- Created a clean, analysis-ready dataset for SQL and Power BI analysis